{
    'name': 'Sahyog - Volunteer Management',
    'version': '19.0.1.0.1',
    'category': 'Human Resources',
    'summary': 'Volunteer management for ashram Guest Care department',
    'description': """
        Sahyog manages volunteers, silence periods, breaks, programs,
        availability, meetings, notifications, and reporting.
    """,
    'author': 'Sahyog Team',
    'license': 'LGPL-3',
    'depends': [
        'hr',
        'hr_holidays',
        'calendar',
        'portal',
        'base',
        'mail',
        'auth_oauth',
        'auth_signup',
    ],
    'data': [
        # Security
        'security/sahyog_security.xml',
        'security/ir.model.access.csv',
        # Views
        'views/hr_employee_views.xml',
        'views/sub_team_views.xml',
        'views/region_views.xml',
        'views/tag_views.xml',
        'views/silence_period_views.xml',
        'views/break_period_views.xml',
        'views/program_views.xml',
        'views/program_schedule_views.xml',
        'views/volunteer_program_views.xml',
        'views/calendar_entry_views.xml',
        'views/meeting_views.xml',
        'views/notification_views.xml',
        'views/registration_link_views.xml',
        'views/unavailability_slot_views.xml',
        'views/cron_log_views.xml',
        'views/dashboard_views.xml',
        'views/gantt_views.xml',
        'views/csv_import_wizard_views.xml',
        'views/menu_views.xml',
        # Portal & Registration Templates
        'views/portal_templates.xml',
        'views/registration_templates.xml',
        'views/login_templates.xml',
        # Data (seed)
        'data/region_data.xml',
        'data/volunteer_type_data.xml',
        'data/language_data.xml',
        'data/program_data.xml',
        'data/cron_data.xml',
        'data/mail_template_data.xml',
        'data/oauth_data.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'sahyog/static/src/dashboard/sahyog_dashboard.js',
            'sahyog/static/src/dashboard/sahyog_dashboard.xml',
            'sahyog/static/src/gantt/gantt_helpers.js',
            'sahyog/static/src/gantt/gantt_timeline.js',
            'sahyog/static/src/gantt/gantt_timeline.xml',
            'sahyog/static/src/gantt/gantt_timeline.css',
            'sahyog/static/src/sidebar_toggle/sidebar_toggle.js',
            'sahyog/static/src/sidebar_toggle/sidebar_toggle.xml',
            'sahyog/static/src/sidebar_toggle/sidebar_toggle.scss',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'post_init_hook': '_assign_volunteer_group',
}
